---
title: "Compare lasso and elastic net"
author: "Jose Alquicira Hernandez"
date: "15 May 2017"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: show
    theme: cerulean
---

# Data processing

Cardiodiff datasets used:

- **Cluster cell labels**: `my.clusters_0.45_Day2.RDS`
- **Expression data**: `Exprs_DCVLnorm_unlog_minus1_pos_Day2.RDS`
- **Differential expressed genes**: `DEseq_Cluster1_vs_OtherClusters_Day2.txt_filtered_pAdjusted_sorted.txt`

Data fatures:

- **Day**: 2
- **Cluster comparison**: 1 versus other clusters


```{r import_libraries}
library(magrittr)
library(reshape2)
library(ggplot2)
library(ggthemes)
```


```{r read_data}
# Read prediction results
results.path <- file.path('..','results','output_lasso_elastic-net_ridge_may19','All_List_c1vs_Remaining_Day2_n100-iterations.RDS')
results <- readRDS(results.path)
```

```{r define_function_GetModelAcc}
GetModelAcc <- function(model){
  model.acc <- model %>% 
  lapply("[", 1) %>%
  lapply("[[", 1) %>% 
  lapply("[[", 1) %>% 
  unlist()
  
  model.inacc <- model %>% 
  lapply("[", 1) %>%
  lapply("[[", 1) %>% 
  lapply("[[", 2) %>% 
  unlist()
  
  return(data.frame(accurate = model.acc, inaccurate = model.inacc))
}
```

```{r get_accuracy}
elastic.net.0.1.acc <- GetModelAcc(model = results$elastic.net.0.1)
elastic.net.0.5.acc <- GetModelAcc(model = results$elastic.net.0.5)
elastic.net.0.9.acc <- GetModelAcc(model = results$elastic.net.0.9)
lasso.acc <- GetModelAcc(model = results$lasso)
ridge.acc <- GetModelAcc(model = results$ridge)
```




```{r bind_datasets}
models <- rbind(lasso.acc, elastic.net.0.5.acc, elastic.net.0.1.acc, elastic.net.0.9.acc, ridge.acc)

n.bootstrap <- 100

models$model <- c(rep("lasso", n.bootstrap), 
                         rep("elastic net: 0.5", n.bootstrap), 
                         rep("elastic net: 0.1", n.bootstrap), 
                         rep("elastic net: 0.9", n.bootstrap), 
                         rep("ridge", n.bootstrap))
```


# Accuracy comparison


```{r plot_data, comment=FALSE}
ggplot(models, aes(x = model, y = accurate/(accurate + inaccurate), fill = model)) +
  geom_boxplot() +
  geom_point(position = position_jitter(width = 0.2)) +
  ggtitle("Accuracy comparison between Elastic net, Lasso and Ridge", subtitle = paste(n.bootstrap, "bootstrap replicates were performed")) +
  xlab("Model") +
  ylab("Accuracy") +
  theme_minimal() +
  scale_color_brewer()
```

```{r plot_density}
ggplot(models, aes(x = accurate/(accurate + inaccurate), fill = model)) +
  geom_density(alpha = 0.5) + 
  ggtitle("Accuracy comparison between Elastic net, Lasso and Ridge", subtitle = paste(n.bootstrap, "bootstrap replicates were performed")) +
  ylab("Density") +
  xlab("Accuracy") +
  theme_minimal() +
  scale_color_brewer()
```

```{r}
GetGenes <- function(model){
  model %>% 
    lapply("[[", 2) %>% 
    lapply(function(x) nrow(x) - 1) %>% 
    unlist -> n.genes
  return(n.genes)
}
```



```{r}
elastic.net.0.1.ngenes <- GetGenes(model = results$elastic.net.0.1)
elastic.net.0.5.ngenes <- GetGenes(model = results$elastic.net.0.5)
elastic.net.0.9.ngenes <- GetGenes(model = results$elastic.net.0.9)
lasso.ngenes <- GetGenes(model = results$lasso)
ridge.ngenes <- GetGenes(model = results$ridge)
```

```{r}
models.ngenes <- data.frame(elastic.net.0.1 = elastic.net.0.1.ngenes, elastic.net.0.5 = elastic.net.0.5.ngenes, elastic.net.0.9 = elastic.net.0.9.ngenes, lasso = lasso.ngenes, ridge = ridge.ngenes)
```

```{r}
cat(knitr::kable(as.data.frame(unclass(summary(models.ngenes)))), sep = "\n")
```


```{r}
models.ngenes.long <- melt(models.ngenes, variable.name = "model", value.name = "n.genes")
```


```{r}
ggplot(models.ngenes.long, aes(x = model, y = n.genes, fill = model)) +
  geom_boxplot() +
  geom_point(position = position_jitter(width = 0.2)) +
  ggtitle("Number of genes included in models", subtitle = paste(n.bootstrap, "bootstrap replicates were performed")) +
  xlab("Model") +
  ylab("Number of included genes") +
  theme_minimal() +
  scale_color_brewer()
```


```{r}
# Get gene exclusion
total.genes <- mean(models.ngenes$ridge)
prop.excluded.genes <- as.data.frame(apply(models.ngenes, 2, function(x){ 1 - x/total.genes}))

# Get accuracy
models.raw <- list(elastic.net.0.1.acc, elastic.net.0.5.acc, elastic.net.0.9.acc, lasso.acc, ridge.acc)
models.raw %>% 
  lapply(function(x) x$accurate/(x$accurate + x$inaccurate)) %>% 
  as.data.frame() -> models.raw.df 
names(models.raw.df) <- c('elastic.net.0.1', 'elastic.net.0.5', 'elastic.net.0.9', 'lasso', 'ridge')

AccNgenesRatio <- function(acc, ngenes){
  return(acc*ngenes)
}

models.acc.weight <- mapply(AccNgenesRatio, models.raw.df, prop.excluded.genes, SIMPLIFY = TRUE) %>% 
  as.data.frame() %>% 
  melt(variable.name = "model", value.name = "accuracy") 
```

```{r}
ggplot(models.acc.weight[models.acc.weight$model != 'ridge',], aes(x = model, y = accuracy, fill = model)) +
  geom_boxplot() +
  geom_point(position = position_jitter(width = 0.2)) +
  ggtitle("Accuracy weighted by number of genes included in model", subtitle = paste(n.bootstrap, "bootstrap replicates were performed. Note that ridge method is zero as it uses all features")) +
  xlab("Model") +
  ylab("Accuracy*gene inclusion relation") +
  theme_minimal() +
  scale_color_brewer()
```

```{r include=FALSE}
x <- results$lasso[[1]]$list.deviance

ggplot(x[-nrow(x),], aes(x = as.integer(df), y = as.numeric(deviance))) +
  geom_point() +
  geom_smooth() +
  theme_minimal() +
  scale_y_continuous(limits = c(-0.1,1))
```


